### ISSUE TITLE
cal_score formula

### ISSUE THREAD

**Issue by rtmlp** [Kanatoko/HBOS-python#5]
Hi,

Thanks for sharing the code I was wondering why is `abs(max_score)` used in the `calc_score` formula ? What is it's significance ?

```
    def calc_score(self, max_score):
        if max_score == 0:
            max_score = 1

        if self.quantity > 0:
            self.score = 1.0 * self.quantity / (
                (self.range_to - self.range_from) * self.total_data_size * 1.0 / abs(max_score))

```

**Comment by Kanatoko** [comment]
Hello,

I think you are right, it can be removed.
I just have translated Java implementation to python.
See
https://github.com/Markus-Go/rapidminer-anomalydetection/blob/master/src/de/dfki/madm/anomalydetection/evaluator/statistical_based/HistogramBin.java#L109

**Comment by rtmlp** [comment]
Thanks. I am comparing between two features using HBOS method. So, using abs(max_score) didn't make much sense for my application
